name: Go Tests

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Go test
      if: ${{ !startsWith(github.event.head_commit.message, 'Release') }}
      run: |
          # Install our dependencies
          sudo apt-get update || true 
          sudo apt-get install -y zsh tmux fish || true
          brew install fish tmux bash || true

          # Force the time zone so that test output is consistent
          export TZ='America/Los_Angeles' 

          # Work around a weird bug where zsh on ubuntu actions gives that directory 0777 which makes zsh refuse to start
          sudo chmod 0755 -R /usr/share/zsh/ || true

          # Set a consistent hostname so we can run tests that depend on it
          sudo hostname ghaction-runner-hostname || true 
          sudo scutil --set HostName ghaction-runner-hostname || true

          # Set up a tmpfs for ~/.hishtory/ to help tests run faster
          mkdir ~/.hishtory/
          mount -F tmpfs -o size=500M swap ~/.hishtory/ || true
          diskutil apfs create $(hdiutil attach -nomount ram://1024000) RAMDisk || true
          mount -o noatime -t apfs /Volumes/RAMDisk ~/.hishtory/  

          # Run the tests
          make test
    # - name: Setup tmate session
    #   if: ${{ failure() }}
    #   uses: mxschmitt/action-tmate@v3
    #   with:
    #     limit-access-to-actor: true