name: Tests

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Go test
      if: ${{ !startsWith(github.event.head_commit.message, 'Release') }}
      run: |
          sudo apt-get update || true 
          sudo apt-get install -y zsh fish || true
          brew install fish || true
          make test
